services:
  llm:
    extends:
      file: ./docker/services.compose.yml
      service: llm
  faster_whisper:
    extends:
      file: ./docker/services.compose.yml
      service: faster_whisper
  docling:
    extends:
      file: ./docker/services.compose.yml
      service: docling
  translator-backend:
    extends:
      file: ./docker/services.compose.yml
      service: translator-backend
    ports:
      - "8000:8000"
